version: "3"

services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: your_password
            MYSQL_DATABASE: student_subjects
        networks:
            - app_network

    backend:
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
        networks:
            - app_network

    frontend1:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        networks:
            - app_network
        ports:
            - "8081:80"

    frontend2:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        networks:
            - app_network
        ports:
            - "8082:80"

    frontend3:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        networks:
            - app_network
        ports:
            - "8083:80"

    haproxy:
        image: haproxy:latest
        networks:
            - app_network
        ports:
            - "8080:80"
        volumes:
            - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

networks:
    app_network:
        driver: bridge
