version: "3.8"

services:
    app1:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ID: Laravel-Node-1
        networks:
            - laravel_net

    app2:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            NODE_ID: Laravel-Node-2
        networks:
            - laravel_net

    haproxy:
        image: haproxy:latest
        ports:
            - "8080:80"
        volumes:
            - ./docker/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        depends_on:
            - app1
            - app2
        networks:
            - laravel_net

networks:
    laravel_net:
        driver: bridge
